add a non-mutating probe_value method for fast paths
rust-lang/ena pull request #45
Opened 2023-03-07 07:43 UTC by the8472

The new API is needed for optimizations in https://github.com/rust-lang/rust/pull/108815

2023-03-07 07:46 UTC, the8472 commented
Also needs a version bump so we can use it. Can I include that in this PR or should that be done separately?

2023-03-07 09:16 UTC, nnethercote commented
The most recent `ena` change was https://github.com/rust-lang/ena/pull/43, and @nikomatsakis then did a release off https://github.com/rust-lang/ena/pull/44.

2023-03-14 19:52 UTC, nikomatsakis requested changes
I found the comment confusing. What do you think of this version, @the8472 ?

2023-03-14 19:52 UTC, nikomatsakis commented on src/unify/mod.rs
> +    /// This is useful for fast-paths that want to avoid pointer-chasing.
```suggestion
    /// Obtains current value for key without any pointer chasing; may return `None` if key has been union'd.
```

How does this sound?

2023-03-17 08:30 UTC, merged